class Config():
    def __init__(self,):
        self.trainfile = './data/train.csv'
        self.devfile = './data/dev.csv'
        self.vocab_path = './data/char2id.pkl'
        # self.vec_model='data/word2vecModel'
        self.vec_model = 'data/word2vec'
        self.optimizer='Adam'
        self.lstm_dropout_keep_prob=1.0
        self.word_dropout_keep_prob=1.0
        self.char_dropout_keep_prob =1.0
        self.feature_dropout_keep_prob =1.0
        self.mlp_dropout_keep_prob =1.0
        self.char_num = 1501
        self.feature_size = 39
        self.num_classes = 3
        self.char_sequence_length=202
        self.word_sequence_length=133
        self.char_embedding_dim=400
        self.word_embedding_size = 450
        self.char_lstm_size=400
        self.word_lstm_size = 450
        self.char_attention_size=400
        self.word_attention_size = 450
        self.feature_mlp_size = 100
        self.MLP_size=1000
        self.dev_percentage = 0.1
        self.rate = 1e-3
        self.batch_size=30
        self.batch_size_dev = 100
        self.layer_num = 2
        self.is_train=True
        self.shuffle = True
        self.num_epochs = 100
        self.num_checkpoints = 20
        self.checkpoint = ''
        self.evaluate_every = 90000/self.batch_size
        # self.evaluate_every = 90
        self.checkpoint_every = 2000
        self.num_filters=200
        self.filter_sizes=None
